modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/iGoodie/TwitchSpawn/issues"

[[mods]]
modId="twitchspawn"
version="${file.jarVersion}"
displayName="TwitchSpawn"
authors="iGoodie"
logoFile="pack.png"
description='''
    TwitchSpawn listens for live events related to your Twitch channel using various Socket APIs.
    Then it handles those events with the rules handcrafted by you!
'''

[[dependencies.twitchspawn]]
    modId="forge"
    mandatory=true
    versionRange="[26.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.twitchspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2,)"
    ordering="NONE"
    side="BOTH"
